### ISSUE TITLE
TypeScript Error: Could not find a declaration file for module '@akiyamka/extended-fetch'

### ISSUE THREAD

**Issue by fekoneko** [Akiyamka/extended-fetch#3]
## The problem

I encountered the problem when trying to import this module in my project like so:
`import extendedFetch from "@akiyamka/extended-fetch";`

The message says:
```
  Could not find a declaration file for module '@akiyamka/extended-fetch'.
'<...>/node_modules/@akiyamka/extended-fetch/dist/extended-fetch.js' implicitly has an 'any' type.
  There are types at '<...>/node_modules/@akiyamka/extended-fetch/dist/lib/extended-fetch.d.ts',
but this result could not be resolved when respecting package.json "exports".
The '@akiyamka/extended-fetch' library may need to update its package.json or typings.
```

- TypeScript version: 5.4.5
- Node version: 20.11.1

## My solution

I was able to quickly fix this by adding separate `'types'` fields for ESM and CommonJS exports in the `package.json` (https://stackoverflow.com/a/77566206):
```json
"exports": {
    ".": {
      "import": {
        "types": "./dist/lib/extended-fetch.d.ts",
        "default": "./dist/extended-fetch.js"
      },
      "require": {
        "types": "./dist/lib/extended-fetch.d.ts",
        "default": "./dist/extended-fetch.cjs"
      }
    }
  },
```

I'd really like to use this library and want to help, thank you for your time

**Comment by Akiyamka** [comment]
I apologize for the long silence, and thank you for finding a solution. The fix is included in version 1.0.0
